package de.justeazy.jmdflib.enums;

public enum ConversionType {

	PARAMETRIC_LINEAR, TABULAR_WITH_INTERPOLATION, TABULAR, POLYNOMIAL_FUNCTION, EXPONENTIAL_FUNCTION, LOGARITHMIC_FUNCTION, RATIONAL_CONVERSION_FORMULA, ASAM_MCD2_TEXT_FORMULA, COMPU_VTAB, COMPU_VTAB_RANGE, DATE, TIME, ONE_TO_ONE_FORMULA

}
